version: '2'

services:
  app:
    build: .
    image: example
    command: bin/amber watch
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/example_development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - shards:/app/lib

  migrate:
    build: .
    image: example
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && bin/amber db migrate seed'
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/example_development
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_development
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
  shards:
